pottery: 
	@echo pottery
irrigation: pottery
	@echo irrigation
writing: pottery
	@echo writing
animal_husbandry: 
	@echo animal_husbandry
archery: animal_husbandry
	@echo archery
mining: 
	@echo mining
masonry: mining
	@echo masonry
bronze_working: mining
	@echo bronze_working
the_wheel: mining
	@echo the_wheel
apprenticeship: mining currency horseback_riding
	@echo apprenticeship
sailing: 
	@echo sailing
celestial_navigation: sailing astrology
	@echo celestial_navigation
shipbuilding: sailing
	@echo shipbuilding
astrology: 
	@echo astrology
drama_poetry: astrology irrigation masonry early_empire mysticism
	@echo drama_poetry
theology: astrology mysticism drama_poetry
	@echo theology
horseback_riding: archery
	@echo horseback_riding
machinery: archery iron_working engineering
	@echo machinery
currency: writing foreign_trade
	@echo currency
state_workforce: writing bronze_working craftsmanship
	@echo state_workforce
recorded_history: writing political_philosophy drama_poetry
	@echo recorded_history
construction: masonry the_wheel horseback_riding
	@echo construction
engineering: masonry the_wheel
	@echo engineering
iron_working: bronze_working
	@echo iron_working
mathematics: bronze_working celestial_navigation currency drama_poetry
	@echo mathematics
military_training: bronze_working military_tradition games_recreation
	@echo military_training
cartography: celestial_navigation shipbuilding
	@echo cartography
medieval_faires: currency feudalism
	@echo medieval_faires
guilds: currency feudalism civil_service
	@echo guilds
mercantilism: currency humanism
	@echo mercantilism
stirrups: horseback_riding feudalism
	@echo stirrups
mass_production: shipbuilding machinery education
	@echo mass_production
naval_tradition: shipbuilding defensive_tactics
	@echo naval_tradition
military_tactics: mathematics
	@echo military_tactics
education: mathematics apprenticeship
	@echo education
military_engineering: construction engineering
	@echo military_engineering
castles: construction divine_right exploration
	@echo castles
games_recreation: construction state_workforce
	@echo games_recreation
gunpowder: apprenticeship stirrups military_engineering
	@echo gunpowder
printing: machinery education
	@echo printing
metal_casting: machinery gunpowder
	@echo metal_casting
banking: education stirrups guilds
	@echo banking
astronomy: education
	@echo astronomy
military_science: stirrups printing siege_tactics
	@echo military_science
siege_tactics: castles metal_casting
	@echo siege_tactics
square_rigging: cartography gunpowder
	@echo square_rigging
exploration: cartography mercenaries medieval_faires
	@echo exploration
industrialization: mass_production square_rigging
	@echo industrialization
scientific_theory: banking astronomy the_enlightenment
	@echo scientific_theory
colonialism: astronomy mercantilism
	@echo colonialism
ballistics: metal_casting siege_tactics
	@echo ballistics
economics: metal_casting scientific_theory
	@echo economics
scorched_earth: metal_casting nationalism
	@echo scorched_earth
steam_power: industrialization
	@echo steam_power
flight: industrialization scientific_theory economics
	@echo flight
steel: industrialization rifling
	@echo steel
class_struggle: industrialization ideology
	@echo class_struggle
sanitation: scientific_theory urbanization
	@echo sanitation
rifling: ballistics military_science
	@echo rifling
totalitarianism: military_science ideology
	@echo totalitarianism
electricity: steam_power mercantilism
	@echo electricity
radio: steam_power flight conservation
	@echo radio
chemistry: sanitation
	@echo chemistry
suffrage: sanitation ideology
	@echo suffrage
replaceable_parts: economics
	@echo replaceable_parts
capitalism: economics mass_media
	@echo capitalism
combined_arms: flight combustion
	@echo combined_arms
synthetic_materials: flight plastics
	@echo synthetic_materials
rapid_deployment: flight cold_war
	@echo rapid_deployment
advanced_ballistics: replaceable_parts steel electricity
	@echo advanced_ballistics
combustion: steel natural_history
	@echo combustion
computers: electricity radio suffrage totalitarianism class_struggle
	@echo computers
advanced_flight: radio
	@echo advanced_flight
rocketry: radio chemistry
	@echo rocketry
nanotechnology: radio composites
	@echo nanotechnology
mass_media: radio urbanization
	@echo mass_media
nuclear_program: chemistry ideology
	@echo nuclear_program
plastics: combustion
	@echo plastics
satellites: advanced_flight rocketry
	@echo satellites
globalization: advanced_flight rapid_deployment space_race
	@echo globalization
guidance_systems: rocketry advanced_ballistics
	@echo guidance_systems
space_race: rocketry cold_war
	@echo space_race
nuclear_fission: advanced_ballistics combined_arms
	@echo nuclear_fission
telecommunications: computers
	@echo telecommunications
robotics: computers globalization
	@echo robotics
lasers: nuclear_fission
	@echo lasers
cold_war: nuclear_fission ideology
	@echo cold_war
composites: synthetic_materials
	@echo composites
stealth_technology: synthetic_materials
	@echo stealth_technology
social_media: telecommunications professional_sports space_race
	@echo social_media
nuclear_fusion: lasers
	@echo nuclear_fusion
code_of_laws: 
	@echo code_of_laws
craftsmanship: code_of_laws
	@echo craftsmanship
foreign_trade: code_of_laws
	@echo foreign_trade
military_tradition: craftsmanship
	@echo military_tradition
early_empire: foreign_trade
	@echo early_empire
mysticism: foreign_trade
	@echo mysticism
political_philosophy: state_workforce early_empire
	@echo political_philosophy
defensive_tactics: games_recreation political_philosophy
	@echo defensive_tactics
humanism: drama_poetry medieval_faires
	@echo humanism
mercenaries: military_training feudalism
	@echo mercenaries
feudalism: defensive_tactics
	@echo feudalism
civil_service: defensive_tactics recorded_history
	@echo civil_service
divine_right: theology civil_service
	@echo divine_right
diplomatic_service: guilds
	@echo diplomatic_service
reformed_church: guilds divine_right
	@echo reformed_church
the_enlightenment: humanism diplomatic_service
	@echo the_enlightenment
civil_engineering: mercantilism
	@echo civil_engineering
nationalism: the_enlightenment
	@echo nationalism
opera_ballet: the_enlightenment
	@echo opera_ballet
natural_history: colonialism
	@echo natural_history
urbanization: civil_engineering nationalism
	@echo urbanization
conservation: natural_history urbanization
	@echo conservation
mobilization: urbanization
	@echo mobilization
cultural_heritage: conservation
	@echo cultural_heritage
ideology: mass_media mobilization
	@echo ideology
professional_sports: ideology
	@echo professional_sports
